// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jeceeedkimtrmbkygcoq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImplY2VlZWRraW10cm1ia3lnY29xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MDMyNzgsImV4cCI6MjA2ODQ3OTI3OH0.pX3lsARrDKlha31lGTP-z4DqvJJKFhx9wyVzRl7Ot60";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});